### ISSUE TITLE
AWS to IBM MQ

### ISSUE THREAD

**Issue by awsdatalake** [yurist/mqlambdatm#1]
This looks Great..Thank you..Just want to check if you have solution for other way around -- Sending messages from AWS to IBM MQ on premises..Please advise..

**Comment by yurist** [comment]
Thanks for your interest. To your question - I thought that AWS to MQ on premises direction can be served by regular MQ queue manager to queue manager architecture, using regular MQ triggering or any other mechanism on the premises side. Can you provide a bit of details about your use case?

**Comment by awsdatalake** [comment]
Thank you for quick response..yes we have the MQ queue mgr on premises..how ever I am interested in the work needed on the AWS side to send messages..i.e do we need ibm mq client , libraries etc to post messages from AWS lambda.. please appreciate if there are sample code..Thanks again..

**Comment by yurist** [comment]
- Yes, you need MQ libraries
- You need to code your lambda in Java since MQ Java library is the only one you can safely package in a lambda. MQ library for Java is just a jar that can be packaged inside your package, other libraries are native and I am not sure a native library can be easily packaged into lambda.
- The example of build and package of a lambda that uses JMS API and MQ client libraries is [here](https://github.com/yurist/mqlambdatm-demo) Look especially at [this pom.xml](https://github.com/yurist/mqlambdatm-demo/blob/master/lambda-function-sample/generic-message-handler/pom.xml) - the way it installs MQ client jar. You can use the sample project maven build virtually one-to-one. Other than that, code your lambda as a regular JMS client as you would on premises.
- Before building your code, make sure to install IBM MQ - either full or redistributable client. The demo home page has instructions.

**Comment by awsdatalake** [comment]
Thanks a lot.. Really appreciate it..
